name: 'Upload Build to SideStore Connect'
description: 'Uploads a new build for an app to the specified SideStore Connect instance'
inputs:
  instance_url:
    description: 'Base URL of your SideStore Connect instance'
    required: true
    default: 'https://connect.sidestore.io'
  access_token:
    description: 'Your personal access token'
    required: true
  app_bundle_id:
    description: The app's bundle identifier
    required: true
  app_version:
    description: 'The app version number for which this build should be uploaded'
    required: true
  release_channel:
    description: 'The release channel for the version if a new version should be created'
    required: false
  version_description:
    description: 'App version description to show in the store'
    required: false
  allow_create_new_version:
    description: 'Boolean indicating whether a new version can be created when the `version` does not already exist'
    required: true
    default: true
  publish:
    description: 'Boolean indicating whether to publish the app version after uploading'
    required: true
    default: false
  app_file:
    description: 'The file path to the compiled app'
    required: true
    default: 'App.ipa'
runs:
  using: 'node16'
  main: 'index.js'